services:
  - type: web
    name: sommelier-na-fazenda
    env: node
    buildCommand: cd vinho-em-maos-react && rm -rf node_modules package-lock.json && npm install && npm run build
    startCommand: cd .. && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_PASSWORD
        value: sommelier2026