services:
  - type: web
    name: sommelier-na-fazenda
    env: node
    buildCommand: npm install && rm -rf vinho-em-maos-react/node_modules && cd vinho-em-maos-react && npm install --force && npm run build
    startCommand: cd .. && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_PASSWORD
        value: sommelier2026